import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CropService } from '../crop.service';
import { OrderService } from '../order.service';  // Make sure to create this service
import Swal from 'sweetalert2';
@Component({
  selector: 'app-order',
  templateUrl: './order.component.html',
  styleUrls: ['./order.component.css']
})
export class OrderComponent implements OnInit {

  order: any;

  constructor(
    private route: ActivatedRoute,
    private cropService: CropService,
    private orderService: OrderService,  // Service for order operations
    private router: Router
  ) { }

  ngOnInit(): void {
    const cropId = this.route.snapshot.paramMap.get('cropId');
    if(cropId) {
        this.loadOrderDetail(cropId);
    }
  }

  loadOrderDetail(cropId: string): void {
    this.cropService.getCropById(cropId).subscribe(
      data => {
          this.order = {
              orderId: data.orderId,  // This will be generated by the backend
              cropId: data.cropId,
              quantity: data.quantity,  // Or set a default value
              totalAmount: data.price  // Simple price x quantity calculation
          };
      },
      error => console.error('Error fetching crop details', error)
    );
  }

  // payForOrder(): void {
  //   this.router.navigate(['/payment-form']);
  // }

  saveOrder(): void {
    this.orderService.createOrder(this.order).subscribe(
      data => {
          console.log('Order saved successfully', data);
          Swal.fire({
            title: 'Order saved successfully',
            icon: 'success',
          });
          this.router.navigate(['/payment-form']);
      },
      error => {
          console.error('Error creating order', error);
          alert("order declined")
      }
    );
  }
}
